name: Azure Functions Sample CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:  
  test:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET (global.json)
        uses: actions/setup-dotnet@v3
      - name: Build 
        run: dotnet build ./AzureFunctionsTest/AzureFunctionsTest.sln
      - name: Test
        run: dotnet test ./AzureFunctionsTest/AzureFunctionsTest.sln